---
title: "compute and format pe data"
author: "Dominick Lemas & Hailey Ballard"
date: "01/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        January 08, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R 4.1.2 (2020-10-10)
# version: Rstudio 2021.09.1 Build 372  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) compute and format the pe data.

# Citation for ICD9 PE codes: https://www.ncbi.nlm.nih.gov/books/NBK442039/table/sb222.t7/

```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)
library(fuzzyjoin)

```


```{r, message=FALSE}

# pe_codes: import icd-code information (1:1 structure)
source("~/ehr-preeclampsia-model/code/utils/params.R")

# df: import perinatal icd-code EHR data (1:n structure)
load("~/ehr-preeclampsia-model/data/processed/mom_perinatal_raw.rda")

# delivery_final_v1: import linked delivery data (1:1 structure)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v1.rda")

```

```{r, message=FALSE}

# PREP ICD CODE 1:N DATA

# ICD outcomes
pe_all=pe_codes$perinatal_dx_code

# EHR data
ehr_codes=df %>%
  filter(perinatal_dx_type=="ENCOUNTER")

# create logic: 1= match %in% outcomes, 0= no match  
ehr_pe = ehr_codes %>%
  mutate(pe_logic=if_else(perinatal_dx_code %in% pe_all, 1, 0)) 

# Subset to multiple EHR
pe_subset= ehr_pe %>%
  filter(pe_logic==1) 

# IDs
mom_unique=unique(pe_subset$mom_id)

```


```{r, message=FALSE}

# PREP the DELIVERY 1:1 Data

# rename data
data_final=delivery_final_v1 %>%
  select(mom_id,part_dob,gest_start_date) %>%
  mutate(ehr_logic=if_else(mom_id %in% mom_unique, 1, 0)) %>%
  filter(ehr_logic==1) %>%
  group_by(mom_id,part_dob) %>% slice(1)

```

```{r, message=FALSE}

# START LOOP (RUN on UFRC)
chunks=length(unique(mom_unique)) 
pages <- list()

for(i in 1:chunks){
  
  # subset data
  codes_subset=mult_subset %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  delivery_subset=data_final %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  fuzzy=fuzzy_left_join(codes_subset,delivery_subset,
                        by = c("mom_id" = "mom_id",
                               "perinatal_dx_date" = "part_dob",
                               "perinatal_dx_date"="gest_start_date"),
                        match_fun = list(`==`, `<=`, `>=`)) %>%
    select(-multiple_logic.x,-multiple_logic.y,-mom_id.y)
  pages[[i]] <- fuzzy
} # END LOOP

data_ready=bind_rows(pages) %>%
  rename("mom_id"="mom_id.x")

multgest_dx_dob_v0=data_ready

# file name
file_name="multiple_codes_dob_v0.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
multgest_dx_dob_v0 %>% save(multgest_dx_dob_v0, file=data_export_path)

```

2A - Mild PE
```{r, message=FALSE}
outcomes_mild_pe=c("642.7", "O14.05", "O14.95", "642.df$f71", "O11.4", "O11.9", "O14.90", "O11.3", "642.41", "O11.2", "O14.93", "642.44", "642.4", "643.73", "642.43", "642.4", "642.7", "O14.02", "642.73", "O11.3", "O14.03", "O14.04", "O11.5", "642.42", "014.94", "O14.00", "O14.10", "O14.12", "O14.13", "O14.14", "O14.15", "642.50", "642.5", "642.51", "642.52", "642.53", "642.54")

length(unique(df_codes$part_id))


# create logic: 1= match %in% outcomes, 0= no match  
df_codes = df_codes %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_mild_pe, 1, 0)) 

names(df_codes)[names(df_codes) == "multiple_logic"] <- "mild_pe"
 
```

2B - Severe PE
```{r, message=FALSE}
#Code 1=Severe PE, 0= Mild PE

outcomes_severepe=c("O14.10", "O14.12", "O14.13", "O14.14", "O14.15", "642.50", "642.5", "642.51", "642.52", "642.53", "642.54")


# create logic: 1= match %in% outcomes, 0= no match  
df_codes = df_codes %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_severepe, 1, 0)) 

names(df_codes)[names(df_codes) == "multiple_logic"] <- "severe_pe"
```


Output 6 - Uncomplicated Hypertension 
```{r, message=FALSE}

outcomes_hypertension=c("O13.3", "642.31", "642.33", "O13.9", "O16.3", "O16.9", "O16.1", "O16.2", "O13.2", "O13.1")

# create logic: 1= match %in% outcomes, 0= no match  
df_codes = df_codes %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_hypertension, 1, 0)) 

names(df_codes)[names(df_codes) == "multiple_logic"] <- "hypertension"
```


Output 7 - Complicated Diabetes
```{r, message=FALSE}

outcomes_complicated_diabetes=c("648", "648.03", "648.01", "648.02", "648.04")

# create logic: 1= match %in% outcomes, 0= no match  
df_codes = df_codes %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_complicated_diabetes, 1, 0)) 

names(df_codes)[names(df_codes) == "multiple_logic"] <- "complicated_diabetes"
```

Output 8 - Uncomplicated Diabetes
```{r, message=FALSE}

outcomes_complicated_diabetes=c("O24.912", "O24.419", "O24.410", "O24.415", "O24.425", "O24.429", "O24.12", "O24.33", "O24.113", "O24.13", "O24.02", "O24.013", "O24.019", "O24.012", "O24.011", "O24.111", "O24.112", "O24.312", "O24.913", "O24.420", "O24.414", "O24.424", "O24.439", "O24.313", "O24.82", "O24.430", "O24.919", "O24.911", "O24.311", "O24.811", "O24.92", "O24.435", "O24.03", "O24.119", "O24.319", "O24.813", "O24.93", "O24.819", "O24.32")

# create logic: 1= match %in% outcomes, 0= no match  
df_codes = df_codes %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_complicated_diabetes, 1, 0)) 

names(df_codes)[names(df_codes) == "multiple_logic"] <- "complicated_diabetes"
```
