---
title: "format gestational-age"
author: "Dominick Lemas"
date: "01/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        January 07, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) format the gestational-age data.
```

```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(dplyr)
```


```{r, message=FALSE}

# load linked: clinical-gravid/parity data
# should be delivery: 22075 unique moms & 28530 unique kids

load("~/ehr-preeclampsia-model/data/processed/mombaby_linked_clinical.rda")

# data inventory
# 22075 unique moms and 28530 unique kids. there are 15 duplicates. need to follow-up
length(unique(delivery$baby_id))
length(unique(delivery$mom_id.x))

# duplicate follow-up. Look in raw data (gravid/parity and delivery data to untangle issues)
# code solution upstream with data formatting. re-run data. 
multi=which(duplicated(delivery$baby_id))
df=delivery %>% filter(row_number() %in% multi)
df$mom_id.x

```

```{r, message=FALSE}
# gestational-age
df=delivery %>%
  mutate(baby_gest_age=as_factor(baby_gest_age)) %>%
    arrange(baby_gest_age)
levels(df$baby_gest_age)

df1=df %>%
  mutate(baby_gest_age=dplyr::recode_factor(baby_gest_age, 
                                            "25.5" = "25 5/7",
                                            "28.2" = "28 2/7",
                                            "28.9" = "29",
                                            "30.9" = "31",
                                            "31.3" = "31 3/7",
                                            "31.8" = "32",
                                            "32.6" = "32 6/7",
                                            "33.4" = "33 4/7",
                                            "34.1" = "34 1/7",
                                            "34.2" = "34 2/7",
                                            "34.5" = "34 5/7",
                                            "34.7" = "35",
                                            "35.5" = "35 5/7",
                                            "35.8" = "36",
                                            "35.9" = "36",
                                            "36.2" = "36 2/7",
                                            "36.4" = "36 4/7",
                                            "36.6" = "36 6/7",
                                            "36.9" = "37",
                                            "37.1" = "37 1/7",
                                            "37.2" = "37 2/7",
                                            "37.3" = "37 3/7",
                                            "37.4" = "37 4/7",
                                            "37.5" = "37 5/7",
                                            "38.2" = "38 2/7",
                                            "38.3" = "38 3/7",
                                            "39.1" = "39 1/7",
                                            "39.5" = "39 5/7",
                                            "38.1" = "38 1/7",
                                            "38.4" = "38 4/7",
                                            "38.5" = "38 5/7",
                                            "38.9" = "39",
                                            "39.2" = "39 2/7",
                                            "39.3" = "39 3/7",
                                            "39.6" = "39 6/7",
                                            "39.7" = "40",
                                            "40.1" = "40 1/7",
                                            "40.2" = "40 2/7",
                                            "40.3" = "40 3/7",
                                            "40.4" = "40 4/7",
                                            "40.6" = "40 6/7",
                                            "41.1" = "41 1/7",
                                            "40.7" = "41",
                                            "41.8" = "42",
                                            "84 1/7" = NA_character_,
                                            "102 2/7" = NA_character_
                                            )) %>%
    arrange(baby_gest_age)
    # levels(df1$baby_gest_age)
```

```{r, message=FALSE}


  arrange(part_id, perinatal_dx_date) %>%



outcomes=c("651","652","O30","O30.0","O30.1",
           "O30.2","O30.8","O30.9","O31")

```


```{r, message=FALSE}
# codes: pre-eclampsia

outcomes=c("651","652","O30","O30.0","O30.1",
           "O30.2","O30.8","O30.9","O31")

```


```{r, message=FALSE}

# cancer outcomes

variables=c("part_id","cancer_dx_date",
                    "cancer_dx_code","cancer_dx_descrip","cancer_dx_type",
                    "cancer_icd_code","cancer_dx_code_type")

# column types.
col_types <- readr::cols(
      part_id  = readr::col_character(),
      redcap_event_name = readr::col_factor(),
      redcap_repeat_instrument = readr::col_factor(),
      redcap_repeat_instance = readr::col_factor(),
      cancer_dx_date = readr::col_date(),
      cancer_dx_code = readr::col_factor(),
      cancer_dx_descrip  = readr::col_character(),
      cancer_dx_type = readr::col_factor(),
      cancer_icd_code = readr::col_factor(),
      cancer_dx_code_type = readr::col_factor()
     )

# participant records
records=mom_list

```

```{r, message=FALSE}

# pull data
start_time = Sys.time()
df=getData_redcap(api_token,uri,records,variables,col_types) %>%
  filter(redcap_repeat_instrument=="diagnosis_codes") %>% as_tibble() 
end_time = Sys.time()
end_time - start_time


```
```{r, message=FALSE}

# exploratory analysis

ggplot(df, aes(x = cancer_dx_code)) +
  geom_bar()

```



```{r, message=FALSE}
## EXPORT to Sharedrive

# file name
file_name="out1.rda"
#data_check_directory=paste0("~/mombaby-ehr-nlp/data/processed/redcap_check/") 
data_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/project/pe_prediction/")
data_path=paste0(data_directory,file_name)
df %>% save(df, file=data_path)

```