---
title: "compute and format multiples"
author: "Dominick Lemas"
date: "01/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        January 07, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) compute and format the multiples data.
```

```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(dplyr)
library(readxl)

```


```{r, message=FALSE}

# import code variables
n_max=1000000
data.file.name="perinatal_ICD_codes_rawdata_01_2022.xlsx"
data.dir=paste0("~/ehr-preeclampsia-model/documents/datadictionary/")
data_import_directory=paste0(data.dir,data.file.name)


# read data
multiple=read_xlsx(data_import_directory, sheet = "multiples", range = NULL, col_names = TRUE,
          col_types = NULL, na = "NA", trim_ws = TRUE, skip = 0, n_max = Inf,
          guess_max = min(1000, n_max))
```

```{r, message=FALSE}

# load data
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v0.rda")
load("~/ehr-preeclampsia-model/data/processed/mom_perinatal_raw.rda")


# rename data
data_link=deliv_final
perinatal_ehr_codes=df
multiple_codes=multiple

```

```{r, message=FALSE}
# gestational-age
df=delivery %>%
  mutate(baby_gest_age=as_factor(baby_gest_age)) %>%
    arrange(baby_gest_age)
  # levels(df$baby_gest_age)

df1=df %>%
  mutate(baby_gest_age=dplyr::recode_factor(baby_gest_age, 
                                            "25.5" = "25 5/7",
                                            "28.2" = "28 2/7",
                                            "28.9" = "29",
                                            "30.9" = "31",
                                            "31.3" = "31 3/7",
                                            "31.8" = "32",
                                            "32.6" = "32 6/7",
                                            "33.4" = "33 4/7",
                                            "34.1" = "34 1/7",
                                            "34.2" = "34 2/7",
                                            "34.5" = "34 5/7",
                                            "34.7" = "35",
                                            "35.5" = "35 5/7",
                                            "35.8" = "36",
                                            "35.9" = "36",
                                            "36.2" = "36 2/7",
                                            "36.4" = "36 4/7",
                                            "36.6" = "36 6/7",
                                            "36.9" = "37",
                                            "37.1" = "37 1/7",
                                            "37.2" = "37 2/7",
                                            "37.3" = "37 3/7",
                                            "37.4" = "37 4/7",
                                            "37.5" = "37 5/7",
                                            "38.2" = "38 2/7",
                                            "38.3" = "38 3/7",
                                            "39.1" = "39 1/7",
                                            "39.5" = "39 5/7",
                                            "38.1" = "38 1/7",
                                            "38.4" = "38 4/7",
                                            "38.5" = "38 5/7",
                                            "38.9" = "39",
                                            "39.2" = "39 2/7",
                                            "39.3" = "39 3/7",
                                            "39.6" = "39 6/7",
                                            "39.7" = "40",
                                            "40.1" = "40 1/7",
                                            "40.2" = "40 2/7",
                                            "40.3" = "40 3/7",
                                            "40.4" = "40 4/7",
                                            "40.6" = "40 6/7",
                                            "41.1" = "41 1/7",
                                            "40.7" = "41",
                                            "41.8" = "42",
                                            "84 1/7" = NA_character_,
                                            "102 2/7" = NA_character_
                                            )) %>%
    arrange(baby_gest_age)
    # levels(df1$baby_gest_age)
```

```{r, message=FALSE}


df2=df1 %>%
  mutate(baby_gest_age_raw=baby_gest_age) %>%
    separate(baby_gest_age, c("weeks", "days")) %>%
  select(mom_id.x,baby_id,part_dob,baby_gest_age_raw,weeks,days,gravidity,parity,everything())

deliv_final=df2


# file name
file_name="delivery_linked_v0.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
deliv_final %>% save(deliv_final, file=data_export_path)

```


