---
title: "Filter Dataset for PE diagnoses"
author: "Hailey Ballard"
date: "01/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Hailey Ballard
# Date:        January 25, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R 4.1.2 (2020-10-10)
# version: Rstudio 2021.09.1 Build 372  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) Filter the complete dataset for ONLY individuals who have PE

```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)
library(fuzzyjoin)
library(dplyr)
library(sjmisc)
library(data.table)
```

```{r, message=FALSE}

# pe_codes: import icd-code information (1:1 structure)
source("~/ehr-preeclampsia-model/code/utils/params.R")

# delivery_final_v8: import linked delivery data (1:1 structure)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v2.rda")
load("~/ehr-preeclampsia-model/data/raw/mom_perinatal_raw.rda")

```

```{r, message=FALSE}

#remove any duplicated baby IDs
delivery_final_v9=delivery_final_v2[!duplicated(delivery_final_v2$baby_id), ]

#filter codes for PE
df_filtered=df%>%
  filter(grepl("pre-eclampsia|Pre-eclampsia", perinatal_dx_descrip))


#select ID and PE diagnosis
df_filtered=df_filtered%>%
  select(part_id, perinatal_dx_date, perinatal_dx_descrip)

#Add year of PE diagnosis to PART ID
df_filtered=df_filtered%>%
  mutate(year=lubridate::year(perinatal_dx_date))

df_filtered$part_id<-paste(df_filtered$part_id, df_filtered$year, sep = "_")

df_filtered=df_filtered%>%
  group_by(part_id)%>%
  arrange(part_id)%>%
  slice(1L)%>%
  select(-year)

#Add year of delivery to PART ID
delivery_final_v9=delivery_final_v9%>%
  mutate(year=lubridate::year(part_dob))

delivery_final_v9$mom_id<-paste(delivery_final_v9$mom_id, delivery_final_v9$year, sep = "_")

df_filtered=df_filtered%>%
  rename(mom_id = part_id)

df_filtered=df_filtered%>%
  group_by(mom_id)%>%
  arrange(mom_id)%>%
  slice(1L)

delivery_final_v9=delivery_final_v9%>%
  filter(mom_id %in% df_filtered$mom_id)%>%
  #select(-year)%>%
  group_by(mom_id)%>%
  arrange(mom_id)%>%
  slice(1L)

df_filtered=df_filtered%>%
  filter(mom_id %in% delivery_final_v9$mom_id)


delivery_final_v9<-merge(delivery_final_v9, df_filtered, by="mom_id")

#calculate time between delivery and first PE diagnosis
for(x in delivery_final_v9$mom_id){
  delivery_final_v9$time_to_deliver=paste(difftime(delivery_final_v9$part_dob, delivery_final_v9$perinatal_dx_date, units="days"))
}

#delivery_final_v9=delivery_final_v9%>%
 # filter(between(delivery_final_v9$time_to_deliver, 0, 150))
#
delivery_final_v9=delivery_final_v9%>%
  mutate(delivery_final_v9, mom_id=sapply(strsplit(delivery_final_v9$mom_id, split="_", fixed=TRUE), function(x) (x[1])))

#delivery_final_v9=delivery_final_v9%>%
#  filter(delivery_final_v9$prenatal_pe_logic == "preeclampsia")

delivery_final_v9=delivery_final_v9%>%
  group_by(mom_id)

delivery_final_v9$past_pe<-ifelse(!(duplicated(delivery_final_v9$mom_id)), "0", "1")

delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver >= 0, ]

delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 177, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 153, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 156, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 162, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 166, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 167, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 169, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 181, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 184, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 188, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 192, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 197, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 205, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 209, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 212, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 216, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 222, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 224, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 306, ]
delivery_final_v9<-delivery_final_v9[delivery_final_v9$time_to_deliver != 324, ]


delivery_final_v9=delivery_final_v9%>%
  subset(part_dob>"2015-10-01")

```

```{r, message=FALSE}
# file name
file_name="delivery_linked_v9.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_final_v9 %>% save(delivery_final_v9, file=data_export_path)
```

