---
title: "Filter Final Dataset for PE"
author: "Hailey Ballard"
date: "01/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Hailey Ballard
# Date:        January 25, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R 4.1.2 (2020-10-10)
# version: Rstudio 2021.09.1 Build 372  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) Filter the complete dataset for ONLY individuals who have PE

```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)
library(fuzzyjoin)
library(dplyr)
library(sjmisc)
library(data.table)
library(lubridate)
```

```{r, message=FALSE}

# pe_codes: import icd-code information (1:1 structure)

mom_alcohol_release<-read_csv("C:/Users/haile/OneDrive/UM/ehr-preeclampsia-model/data/raw/mom_alcohol_release.csv")

mom_comorbidities_icd10<-read_csv("C:/Users/haile/OneDrive/UM/ehr-preeclampsia-model/data/raw/mom_comorbidities_list_ICD10_release.csv")

mom_comorbidities_icd9<-read_csv("C:/Users/haile/OneDrive/UM/ehr-preeclampsia-model/data/raw/mom_comorbidities_list_ICD9_release.csv")

#load delivery final v9
load("C:/Users/haile/OneDrive/UM/ehr-preeclampsia-model/data/processed/delivery_linked_v9.rda")

mom_comorbidities_codes<-rbind(mom_comorbidities_icd10, mom_comorbidities_icd9)
mom_comorbidities_codes$Deidentified_mom_ID<-paste0("mom-", mom_comorbidities_codes$Deidentified_mom_ID)

mom_alcohol_release$Deidentified_mom_ID<-paste0("mom-",mom_alcohol_release$Deidentified_mom_ID)

mom_comorbidities_codes$`Diagnosis Start Date`<-as.factor(mom_comorbidities_codes$`Diagnosis Start Date`)
mom_comorbidities_codes$`Diagnosis Start Date`<-strptime(mom_comorbidities_codes$`Diagnosis Start Date`, format="%m/%d/%y")
mom_comorbidities_codes$`Diagnosis Start Date`<-as.Date(mom_comorbidities_codes$`Diagnosis Start Date`, format="%m-%d-%y")

delivery_final_v9=delivery_final_v9%>%
  mutate(year=lubridate::year(part_dob))

delivery_final_v9$mom_id<-paste(delivery_final_v9$mom_id, delivery_final_v9$year, sep = "_")

```

#Severe PE
```{r}

delivery_final_v9$SeverePE<-ifelse(grepl("Severe pre-eclampsia", delivery_final_v9$perinatal_dx_descrip), "1", "0")

```
#Alcohol Yes and Never
```{r, message=FALSE}
#history of alcohol use
alcohol_use=mom_comorbidities_codes%>%
  filter(stringr::str_starts(mom_comorbidities_codes$`Diagnosis Code`, "F10|K29|K70.0|K70.3|K70.9|291.8|291.9|303.0|303.9|305.0|571.1|571.3|571.3|980.9"))

#Add year of delivery to PART ID
alcohol_use=alcohol_use%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

alcohol_use$Deidentified_mom_ID<-paste(alcohol_use$Deidentified_mom_ID, alcohol_use$year, sep = "_")

moms_alcohol=unique(alcohol_use$Deidentified_mom_ID)


delivery_final_v9$AlcoholUseStatusSourceYes<-ifelse(delivery_final_v9$mom_id %in% moms_alcohol, "1", "0")


alcohol_never_comment=mom_alcohol_release%>%
  filter(grepl("Never|never", mom_alcohol_release$`Alcohol Comment`)) 

#Add year of delivery to PART ID
alcohol_never_comment=alcohol_never_comment%>%
  mutate(year=lubridate::year(`Contact Date`)) 

alcohol_never_comment$Deidentified_mom_ID<-paste(alcohol_never_comment$Deidentified_mom_ID, alcohol_never_comment$year, sep = "_")

moms_alcohol_never2=unique(alcohol_never_comment$Deidentified_mom_ID)

delivery_final_v9$AlcoholUseStatusSourceNever<-ifelse(delivery_final_v9$mom_id %in% moms_alcohol_never2, "1", "0")

```

#Alcohol NO
```{r, message=FALSE}

alcohol_use_past=mom_alcohol_release%>%
  filter(grepl("none|prior|None|Prior|before|Before|Not anymore|not anymore|", mom_alcohol_release$`Alcohol Comment`)) 

#Add year of delivery to PART ID
alcohol_use_past=alcohol_use_past%>%
  mutate(year=lubridate::year(`Contact Date`)) 

alcohol_use_past$Deidentified_mom_ID<-paste(alcohol_use_past$Deidentified_mom_ID, alcohol_use_past$year, sep = "_")

moms_alcohol_past=unique(alcohol_use_past$Deidentified_mom_ID)

delivery_final_v9$AlcoholUseStatusNo<-ifelse(delivery_final_v9$mom_id %in% moms_alcohol_past, "1", "0")
```

#Uncomplicated Hypertension
```{r, message=FALSE}
df_hypertension_uncomplicated=mom_comorbidities_codes%>%
  filter(stringr::str_starts(mom_comorbidities_codes$`Diagnosis Code`, "401"))

#Add year of delivery to PART ID
df_hypertension_uncomplicated=df_hypertension_uncomplicated%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

df_hypertension_uncomplicated$Deidentified_mom_ID<-paste(df_hypertension_uncomplicated$Deidentified_mom_ID, df_hypertension_uncomplicated$year, sep = "_")

moms_hypertension=unique(df_hypertension_uncomplicated$Deidentified_mom_ID)

delivery_final_v9$HypertensionUncomplicated<-ifelse(delivery_final_v9$mom_id %in% moms_hypertension, "1", "0")

```

#Uncomplicated Diabetes
```{r, message=FALSE}
df_diabetes_uncomplicated=mom_comorbidities_codes%>%
  filter(stringr::str_starts(mom_comorbidities_codes$`Diagnosis Code`, "E10.0|E10.1|E10.09|E11.0|E11.1|E11.9|E12.0|E12.1|E12.9|E13.0|E13.1|E13.9|E14.0|E14.1|E14.9|250.0|250.1|250.2|250.3"))

#Add year of delivery to PART ID
df_diabetes_uncomplicated=df_diabetes_uncomplicated%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`))

df_diabetes_uncomplicated$Deidentified_mom_ID<-paste(df_diabetes_uncomplicated$Deidentified_mom_ID, df_diabetes_uncomplicated$year, sep = "_")

moms_diabetes_uncomp=unique(df_diabetes_uncomplicated$Deidentified_mom_ID)

delivery_final_v9$DiabetesUncomplicated<-ifelse(delivery_final_v9$mom_id %in% moms_diabetes_uncomp, "1", "0")

```

#Complicated Diabetes
```{r, message=FALSE}
df_diabetes_complicated=mom_comorbidities_codes%>%
  filter(stringr::str_starts(mom_comorbidities_codes$`Diagnosis Code`, "E10.2|E10.3|E10.4|E10.5|E10.6|E10.7|E10.8|E11.2|E11.3|E11.4|E11.5|E11.6|E11.7|E11.8|E12.2|E12.3|E12.4|E12.5|E12.6|E12.7|E12.8|E13.2|E13.3|E13.4|E13.5|E13.6|E13.7|E13.8|E14.2|E14.3|E14.4|E14.5|E14.6|E14.7|E14.8|250.4|250.5|250.6|250.7|250.8|250.9")) 

#Add year of delivery to PART ID
df_diabetes_complicated=df_diabetes_complicated%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`))

df_diabetes_complicated$Deidentified_mom_ID<-paste(df_diabetes_complicated$Deidentified_mom_ID, df_diabetes_complicated$year, sep = "_")

moms_diabetes_comp=unique(df_diabetes_complicated$Deidentified_mom_ID)

delivery_final_v9$DiabetesComplicated<-ifelse(delivery_final_v9$mom_id %in% moms_diabetes_comp, "1", "0")

```

#Illegal Drug Use
```{r, message=FALSE}

drug_use_yes=mom_comorbidities_codes%>%
  filter(stringr::str_starts( mom_comorbidities_codes$`Diagnosis Code`, "292|304|305.9"))

drug_use_yes_1=drug_use_yes%>%
  filter(!grepl("remission", drug_use_yes$`Diagnosis Description`))

drug_use_past=drug_use_yes%>%
  filter(grepl("remission", drug_use_yes$`Diagnosis Description`))

#Add year of delivery to PART ID
drug_use_yes_1=drug_use_yes_1%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

drug_use_yes_1$Deidentified_mom_ID<-paste(drug_use_yes_1$Deidentified_mom_ID, drug_use_yes_1$year, sep = "_")

moms_drug_use_yes=unique(drug_use_yes_1$Deidentified_mom_ID)

delivery_final_v9$IllegalDrugUserStatusSourceYes<-ifelse(delivery_final_v9$mom_id %in% moms_drug_use_yes, "1", "0")

delivery_final_v9$IllegalDrugUserStatusSourceNever<-ifelse(delivery_final_v9$IllegalDrugUserStatusSourceYes == "1", "0", "1")

#past drug use
#Add year of delivery to PART ID
drug_use_past=drug_use_past%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

drug_use_past$Deidentified_mom_ID<-paste(drug_use_past$Deidentified_mom_ID, drug_use_past$year, sep = "_")

moms_drug_use_past=unique(drug_use_past$Deidentified_mom_ID)

delivery_final_v9$IllegalDrugUserStatusSourceNo<-ifelse(delivery_final_v9$mom_id %in% moms_drug_use_past, "1", "0")

```

#Coagulopathy
```{r}
coagulopathy=mom_comorbidities_codes%>%
  filter(grepl("286|287.1|287.3287.4|287.5|D68|D69.1|D69.3|D69.4|D69.5|D69.6", mom_comorbidities_codes$`Diagnosis Code`)) 

#Add year of delivery to PART ID
coagulopathy=coagulopathy%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

coagulopathy$Deidentified_mom_ID<-paste(coagulopathy$Deidentified_mom_ID, coagulopathy$year, sep = "_")

coagulopathy=unique(coagulopathy$Deidentified_mom_ID)

delivery_final_v9$Coagulopathy<-ifelse(delivery_final_v9$mom_id %in% coagulopathy, "1", "0")

```

#Pulmonary Circulation Disorders
```{r}
PulmonaryCirculationDisorders=mom_comorbidities_codes%>%
  filter(grepl("416|417.9|I27|I28.0|I28.8|415.1", mom_comorbidities_codes$`Diagnosis Code`)) 

#Add year of delivery to PART ID
PulmonaryCirculationDisorders=PulmonaryCirculationDisorders%>%
  mutate(year=lubridate::year(`Diagnosis Start Date`)) 

PulmonaryCirculationDisorders$Deidentified_mom_ID<-paste(PulmonaryCirculationDisorders$Deidentified_mom_ID, PulmonaryCirculationDisorders$year, sep = "_")

PulmonaryCirculationDisorders=unique(PulmonaryCirculationDisorders$Deidentified_mom_ID)

delivery_final_v9$PulmonaryCirculationDisorders<-ifelse(delivery_final_v9$mom_id %in% PulmonaryCirculationDisorders, "1", "0")

```

#clean
```{r}
#drop NAs
delivery_final_v9=delivery_final_v9%>%
  filter(!is.na(weeks)&!is.na(gravidity)&!is.na(parity))

#add column for multiple gestation
delivery_final_v9=delivery_final_v9%>%
  mutate(multiple_gestation=case_when(
    multgest_dx_subcategory == "twin" ~ "2",
    multgest_dx_subcategory == "triplet" ~ "3",
    multgest_dx_subcategory == "quadruplet" ~ "4",
    multgest_dx_subcategory == "multiple" ~ "1",
  ))

delivery_final_v9$multiple_gestation[is.na(delivery_final_v9$multiple_gestation)] <- 1


```

```{r, message=FALSE}
# file name
file_name="delivery_linked_v9.rda"
data_export_directory=paste0("C:/Users/haile/OneDrive/UM/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_final_v9 %>% save(delivery_final_v9, file=data_export_path)
```
