---
title: "compute and format pe data"
author: "Dominick Lemas & Hailey Ballard"
date: "01/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        January 08, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R 4.1.2 (2020-10-10)
# version: Rstudio 2021.09.1 Build 372  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) compute and format the pe data.

# Citation for ICD9 PE codes: https://www.ncbi.nlm.nih.gov/books/NBK442039/table/sb222.t7/

```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)
library(fuzzyjoin)

```

```{r, message=FALSE}

# pe_codes: import icd-code information (1:1 structure)
source("~/ehr-preeclampsia-model/code/utils/params.R")

# df: import perinatal icd-code EHR data (1:n structure)
load("~/ehr-preeclampsia-model/data/processed/pe_codes_dob_v0.rda")

# delivery_final_v1: import linked delivery data (1:1 structure)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v2.rda")

```

```{r, message=FALSE}

# PREP ICD CODE 1:N DATA

# ICD outcomes
code_all=pe_codes$perinatal_dx_code

# EHR data
ehr_codes=pe_dx_dob_v0

# Subset to multiple EHR
ehr_subset= ehr_codes2 %>%
  filter(ehr_logic==1) %>%
  select(-ehr_logic)

# IDs
mom_unique=unique(ehr_subset$mom_id)

```


```{r, message=FALSE}

# PREP the DELIVERY 1:1 Data

# rename data
data_final=delivery_final_v1 %>%
  select(mom_id,part_dob,gest_start_date) %>%
  mutate(ehr_logic=if_else(mom_id %in% mom_unique, 1, 0)) %>%
  filter(ehr_logic==1) %>%
  group_by(mom_id,part_dob) %>% slice(1) %>%
  select(-ehr_logic)

```

```{r, message=FALSE}

# START LOOP (RUN on UFRC)
chunks=length(unique(mom_unique)) 
pages <- list()

for(i in 1:chunks){
  
  # subset data
  codes_subset=ehr_subset %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  delivery_subset=data_final %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  fuzzy=fuzzy_left_join(codes_subset,delivery_subset,
                        by = c("mom_id" = "mom_id",
                               "perinatal_dx_date" = "part_dob",
                               "perinatal_dx_date"="gest_start_date"),
                        match_fun = list(`==`, `<=`, `>=`)) %>%
    select(-mom_id.y)
  pages[[i]] <- fuzzy
} # END LOOP

data_ready=bind_rows(pages) %>%
  rename("mom_id"="mom_id.x")

pe_dx_dob_v0=data_ready

# file name
file_name="pe_codes_dob_v0.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
pe_dx_dob_v0 %>% save(pe_dx_dob_v0, file=data_export_path)

# create Rscript using knitr::purl()

```

```{r, message=FALSE}
# load UFRC linked data

# 1077 unique moms
load("~/ehr-preeclampsia-model/data/processed/pe_dx_dob_v0.rda")

# remove dates past DOB and select the most recent code/visit before DOB. 
dat=pe_dx_dob_v0 %>%
  drop_na() %>% 
        group_by(mom_id,part_dob) %>% 
        filter(perinatal_dx_date == max(perinatal_dx_date))

# link multiple data
ehr_select=pe_codes %>%
  select(perinatal_dx_code,perinatal_dx_category,perinatal_dx_subcategory,perinatal_dx_gestation)

# merge ICD code annotations into ICD data
code_annotate=left_join(
  dat,
  ehr_select,
  by = "perinatal_dx_code",
  copy = FALSE,
  suffix = c(".x", ".y"),
  keep = FALSE)

col_name=names(code_annotate) %>% 
    str_replace_all("perinatal", "pe")

colnames(code_annotate)<-col_name

code_final=code_annotate

```

```{r, message=FALSE}

# ANY PRENATAL PRE_ECLAMPSIA CODE

# MERGE pe data into delivery

# delivery data
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v1.rda")
del_final=delivery_final_v1 

# code-annotations: any-pe status
pe_any=code_final %>% ungroup() %>%
  select(mom_id,part_dob,gest_start_date,pe_dx_date,pe_dx_category)
  

# merge ICD code annotations into ICD data
merge_final=left_join(
  del_final,
  pe_any,
  by = c("mom_id","part_dob"),
  copy = FALSE,
  suffix = c(".x", ".y"),
  keep = FALSE) %>%
  select(-gest_start_date.y) %>%
  rename("gest_start_date"="gest_start_date.x")

delivery_final_v2=merge_final %>%
  select(-pe_dx_date) %>%
  rename("prenatal_pe_logic"="pe_dx_category")

# EXPORT DATA

# file name
file_name="delivery_linked_v2.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_final_v2 %>% save(delivery_final_v2, file=data_export_path)

```


