---
title: "compute and format diabetes data"
author: "Dominick Lemas"
date: "01/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        January 08, 2022
# IRB:         IRB protocol IRB201601899  
#
# version: R 4.1.2 (2020-10-10)
# version: Rstudio 2021.09.1 Build 372  

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

# (1) compute and format the diabetes data.

```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)
# library(fuzzyjoin)

```

```{r, message=FALSE}

# pe_codes: import icd-code information (1:1 structure)
source("~/ehr-preeclampsia-model/code/utils/params.R")

# df: import perinatal icd-code EHR data (1:n structure)
load("~/ehr-preeclampsia-model/data/processed/mom_perinatal_raw.rda")

# delivery_final_v1: import linked delivery data (1:1 structure)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v4.rda")

```

```{r, message=FALSE}

# PREP ICD CODE 1:N DATA

# ICD codes
icd_codes=diab_codes %>%
  filter(perinatal_dx_category=="diabetes") %>% pull(perinatal_dx_code)

# EHR data
ehr_codes=df %>%
  filter(perinatal_dx_type=="ENCOUNTER") %>%
  mutate(ehr_logic=if_else(perinatal_dx_code %in% icd_codes, 1, 0)) %>%
  filter(ehr_logic==1) %>%
  select(-ehr_logic)

# IDs
mom_unique=unique(ehr_codes$mom_id)

```

```{r, message=FALSE}

# PREP the DELIVERY 1:1 Data

data_final=delivery_final_v4 %>%
  select(mom_id,part_dob,gest_start_date) %>%
  mutate(ehr_logic=if_else(mom_id %in% mom_unique, 1, 0)) %>%
  filter(ehr_logic==1) %>%
  group_by(mom_id,part_dob) %>% slice(1) %>%
  select(-ehr_logic)

```

```{r, message=FALSE}

# START LOOP (RUN on UFRC). Does not run in rstudio

chunks=length(unique(mom_unique)) 
pages <- list()

for(i in 1:chunks){
  
  # subset data
  codes_subset=ehr_codes %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  delivery_subset=data_final %>%
    filter(mom_id==mom_unique[i]) %>%
    select(mom_id,everything())
  
  fuzzy=fuzzy_left_join(codes_subset,delivery_subset,
                        by = c("mom_id" = "mom_id",
                               "perinatal_dx_date" = "part_dob",
                               "perinatal_dx_date"="gest_start_date"),
                        match_fun = list(`==`, `<=`, `>=`)) %>%
    select(-mom_id.y)
  pages[[i]] <- fuzzy
} # END LOOP

data_ready=bind_rows(pages) %>%
  rename("mom_id"="mom_id.x")

diab_dx_dob_v0=data_ready

# file name
file_name="diab_codes_dob_v0.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
diab_dx_dob_v0 %>% save(diab_dx_dob_v0, file=data_export_path)

```

```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(tidyverse)
library(readxl)

```

```{r, message=FALSE}

# SWEEP

# pe_codes: import icd-code information (1:1 structure)
source("~/ehr-preeclampsia-model/code/utils/params.R")

# df: import perinatal icd-code EHR data (1:n structure)
load("~/ehr-preeclampsia-model/data/processed/diab_codes_dob_v0.rda")

# delivery_final_v1: import linked delivery data (1:1 structure)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v5.rda")

```

```{r, message=FALSE}

# DIABETES-COMPLICATED

# PREP ICD CODE 1:N DATA

# ICD codes
icd_codes=diab_codes %>%
  filter(perinatal_dx_subcategory=="complicated") %>% pull(perinatal_dx_code)

# Define diab_comp
ehr_logic=diab_dx_dob_v0 %>% ungroup() %>%
  filter(!is.na(part_dob)) %>%               # this (largely) removes postnatal codes
  mutate(diab_comp_logic=if_else(perinatal_dx_code %in% icd_codes, 1, 0))  %>%
  select(mom_id,part_dob,diab_comp_logic) %>% 
  group_by(mom_id,part_dob) %>% 
  summarize(diab_comp = max(diab_comp_logic)) # picks the max value w/in mom-id/DOB

# IDs
mom_unique=unique(ehr_logic$mom_id)

```

```{r, message=FALSE}

# MERGE INTO LATEST DATA VERSION 

# delivery data
del_final=delivery_final_v5 

# ICD-Data: pe-onset status
diab_comp=ehr_logic
  

# merge ICD code annotations into ICD data
merge_final=left_join(
  del_final,
  diab_comp,
  by = c("mom_id","part_dob"),
  copy = FALSE,
  suffix = c(".x", ".y"),
  keep = FALSE) 

# EXPORT DATA
delivery_final_v6=merge_final

# file name
file_name="delivery_linked_v6.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_final_v6 %>% save(delivery_final_v6, file=data_export_path)

```


```{r, message=FALSE}

# DIABETES-UNCOMPLICATED

# PREP ICD CODE 1:N DATA

# ICD codes
icd_codes=diab_codes %>%
  filter(perinatal_dx_subcategory=="uncomplicated") %>% pull(perinatal_dx_code)

# Define diab_uncomp
ehr_logic=diab_dx_dob_v0 %>% ungroup() %>%
  filter(!is.na(part_dob)) %>%               # this (largely) removes postnatal codes
  mutate(diab_uncomp_logic=if_else(perinatal_dx_code %in% icd_codes, 1, 0))  %>%
  select(mom_id,part_dob,diab_uncomp_logic) %>% 
  group_by(mom_id,part_dob) %>% 
  summarize(diab_uncomp = max(diab_uncomp_logic)) # picks the max value w/in mom-id/DOB

# IDs
mom_unique=unique(ehr_logic$mom_id)

```

```{r, message=FALSE}

# MERGE INTO LATEST DATA VERSION 

# delivery data
del_final=delivery_final_v6 

# ICD-Data: pe-onset status
diab_uncomp=ehr_logic
  

# merge ICD code annotations into ICD data
merge_final=left_join(
  del_final,
  diab_uncomp,
  by = c("mom_id","part_dob"),
  copy = FALSE,
  suffix = c(".x", ".y"),
  keep = FALSE) 

# EXPORT DATA
delivery_final_v7=merge_final

# file name
file_name="delivery_linked_v7.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_final_v7 %>% save(delivery_final_v7, file=data_export_path)

```

