---
title: "01 - Get Report Data"
author: "Hailey Ballard"
date: "10/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Hailey Ballard
# Date:        October 21, 2021
# IRB:         IRB protocol IRB201601899  
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073  
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(keyringr)
library(redcapAPI)
library(REDCapR)
library(readxl)
library(tidyverse)
```


```{r, include=FALSE, message=FALSE, warning=FALSE}
# Data Processing Notes

# IDR
release_date="Fri 9/24/2021 9:47 AM"
idr_analyst="Lei McDevitt"
idr_analyst_email="leimcdevitt@ufl.edu"

# Lemas Lab
dataprocessing_date=format(Sys.time(), "%a %b %d %X %Y")
lemaslab_analyst="Hailey Ballard"
lemaslab_analyst_email="hballard@ufl.edu"
lemaslab_code="ehr-preeclampsia-model/code/data_processing/"

```

```{r, message=FALSE}
# Windows
 source("~/ehr-preeclampsia-model/code/utils/utils.R")
 api_token=get_API_token("ehr-database")
```

```{r, message=FALSE}
# Mac, you need to store your API code in your keychain first
# api_token <- decrypt_kc_pw("Redcap_BEACH_analysis")
```

```{r, message=FALSE}
# API and URL
uri='https://redcap.ctsi.ufl.edu/redcap/api/'
rcon <- redcapConnection(url=uri, token=api_token)
report_id <- 27471
# Access data
data_raw=redcap_report(
  uri,
  api_token,
  report_id,
  raw_or_label_headers="raw",
  guess_type=FALSE)$data
# Import the the master codebook
#Var_Ques<-read_excel("~/BEACH-database/documents/beach_codebook_new.xlsx")
#data_raw=data %>%
#  as_tibble()
# Save the data in your local laptop (Github path: /data)
save(list=c("data_raw"),file="~/ehr-preeclampsia-model/data/raw/data_report_raw.RData")
```