---
title: "Perinatal codes - Data cleaning"
author: "Dominick Lemas"
date: "12/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        October 21, 2021
# IRB:         IRB protocol IRB201601899  
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073  
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(keyringr)
library(tidyverse)
library(redcapAPI)
library(REDCapR)
library(dplyr)
library(plyr)
library(ggplot2)
```


```{r, message=FALSE}
# Windows
 source("~/ehr-preeclampsia-model/data/processed/mom_perinatal_codes.rda")
```

Output 2 - Severe PE 
```{r, message=FALSE}
#Code 1=Severe PE, 0= No Severe PE

outcomes_severepe=c("O14.10", "O14.12", "O14.13", "O14.14", "O14.15", "642.50", "642.5", "642.51", "642.52", "642.53", "642.54")

length(unique(df$part_id))

# outcomes
outcomes_severepe

# create logic: 1= match %in% outcomes, 0= no match  
df2 = df %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_severepe, 1, 0)) 

names(df2)[names(df2) == "multiple_logic"] <- "severe_pe"
```

Output 2 - Mild PE
```{r, message=FALSE}
#Code 1= Mild PE, 0=No Mild PE

outcomes_mildpe=c("642.7", "O14.05", "O14.95", "642.71", "O11.4", "O11.9", "O14.90", "O11.3", "642.41", "O11.2", "O14.93", "642.44", "642.4", "643.73", "642.43", "642.4", "642.7", "O14.02", "642.73", "O11.3", "O14.03", "O14.04", "O11.5", "642.42", "014.94", "O14.00")

length(unique(df$part_id))

# outcomes
outcomes_mildpe

# create logic: 1= match %in% outcomes, 0= no match  
df2 = df2 %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_mildpe, 1, 0)) 

names(df2)[names(df2) == "multiple_logic"] <- "mild_pe"
```

Output 3 - Multiples
```{r, message=FALSE}

outcomes_multiples=c("651","652","O30","O30.0","O30.1",
           "O30.2","O30.8","O30.9","O31")

length(unique(df$part_id))

# outcomes
outcomes_multiples

# create logic: 1= match %in% outcomes, 0= no match  
df2 = df2 %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_multiples, 1, 0)) 

names(df2)[names(df2) == "multiple_logic"] <- "multiples"
```


Output 6 - Uncomplicated Hypertension
```{r, message=FALSE}

outcomes_hypertension=c()

length(unique(df$part_id))

# outcomes
outcomes_multiples

# create logic: 1= match %in% outcomes, 0= no match  
df2 = df2 %>%
  mutate(multiple_logic=if_else(perinatal_dx_code %in% outcomes_multiples, 1, 0)) 

names(df2)[names(df2) == "multiple_logic"] <- "multiples"
```

