```{r}

# UF Baseline Time to Diagnosis 
library(dplyr)
library(readr)
library(tidyverse)
library(readxl)
library(fuzzyjoin)
library(sjmisc)
library(data.table)
library(lubridate)
library(mice)


load("C:/Users/haile/OneDrive/ehr-preeclampsia-model/data/processed/timetodiagnosis_v1.rda")

```

#Labs 
```{r}
labs=read_csv("C:/Users/haile/OneDrive/ehr-preeclampsia-model/data/raw/mom_labs.csv")

labs$Deidentified_mom_ID<-paste0("mom-", labs$Deidentified_mom_ID)

names(labs)[names(labs)=="Inferred Specimen Datetime"]<- "lab_date"
names(labs)[names(labs)=="Deidentified_mom_ID"]<- "mom_id"
names(labs)[names(labs)=="Lab Name"]<- "lab_name"
names(labs)[names(labs)=="Lab Result"]<- "value"

labs$lab_date<-as.factor(labs$lab_date)
labs$lab_date2<-strftime(labs$lab_date, format="%Y-%m-%d")
labs$lab_date2<-as.Date(labs$lab_date2)
timetodiagnosis_v1$pregnancy_start_date<-as.Date(timetodiagnosis_v1$pregnancy_start_date)

labs=labs%>%
  mutate(year=lubridate::year(lab_date2))

labs$mom_id<-paste(labs$mom_id, labs$year, sep = "_")
```

#Minimum Hematocrit
```{r}

Hematocrit= labs%>%
  filter(lab_name == "HEMATOCRIT")%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 <= pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(Min_Hematocrit=min(value, na.rm=TRUE))%>%
  select(mom_id,Min_Hematocrit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(Hematocrit,  by=c("mom_id"))

```

#Maximum WBCC
```{r}
WBCC= labs%>%
  filter(lab_name == "WHITE BLOOD CELL COUNT")%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 <= pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(Max_WBCC=max(value, na.rm=TRUE))%>%
  select(mom_id,Max_WBCC)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(WBCC,  by=c("mom_id"))

```

#Minimum MCHC
```{r}
MCHC= labs%>%
  filter(grepl("MCHC", lab_name))%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 <= pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(Min_MCHC=min(value, na.rm=TRUE))%>%
  select(mom_id,Min_MCHC)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(MCHC,  by=c("mom_id"))

```


###### VITALS

```{r}

data_vitals=read_csv("C:/Users/haile/OneDrive/ehr-preeclampsia-model/data/raw/mom_prenatals.csv")

data_full_vitals=read_csv("C:/Users/haile/OneDrive/ehr-preeclampsia-model/data/raw/BP_release.csv")

```

```{r}

data_vitals$Deidentified_mom_ID<-paste0("mom-",data_vitals$Deidentified_mom_ID)

#add year of delivery to mom ID
data_vitals$prenatal_bp_date<-as.Date(data_vitals$`BP Datetime`)
names(data_vitals)[names(data_vitals) == "BP"] <- "prenatal_bp"

delivery_data<-timetodiagnosis_v1
#add year of delivery to mom ID

data_vitals=data_vitals%>%
  mutate(year=lubridate::year(prenatal_bp_date))

data_vitals$Deidentified_mom_ID<-paste(data_vitals$Deidentified_mom_ID, data_vitals$year, sep = "_")

#select mom ID, lab date, and lab type/result
data_vitals=data_vitals%>%
  select(Deidentified_mom_ID, prenatal_bp_date, prenatal_bp)

#rename part_id to mom_id (for merging later)
names(data_vitals)[names(data_vitals) == "Deidentified_mom_ID"] <- "mom_id"

#split systolic (first) and diastolic (second) bp values on /
data_vitals=data_vitals%>%
  separate(prenatal_bp, c("Systolic", "Diastolic"))

#make systolic and diastolic numeric values
data_vitals$Systolic=as.numeric(data_vitals$Systolic)
data_vitals$Diastolic=as.numeric(data_vitals$Diastolic)

######### Full vitals
data_full_vitals$Deidentified_mom_ID<-paste0("mom-",data_full_vitals$Deidentified_mom_ID)

#add year of delivery to mom ID
data_full_vitals$prenatal_bp_date<-as.Date(data_full_vitals$`BP Datetime`)
names(data_full_vitals)[names(data_full_vitals) == "BP"] <- "prenatal_bp"

delivery_data<-timetodiagnosis_v1
#add year of delivery to mom ID

data_full_vitals=data_full_vitals%>%
  mutate(year=lubridate::year(prenatal_bp_date))

data_full_vitals$Deidentified_mom_ID<-paste(data_full_vitals$Deidentified_mom_ID, data_full_vitals$year, sep = "_")

#data_full_vitals mom ID, lab date, and lab type/result
data_full_vitals=data_full_vitals%>%
  select(Deidentified_mom_ID, prenatal_bp_date, prenatal_bp)

#rename part_id to mom_id (for merging later)
names(data_full_vitals)[names(data_full_vitals) == "Deidentified_mom_ID"] <- "mom_id"


#split systolic (first) and diastolic (second) bp values on /
data_full_vitals=data_full_vitals%>%
  separate(prenatal_bp, c("Systolic", "Diastolic"))

#make systolic and diastolic numeric values
data_full_vitals$Systolic=as.numeric(data_full_vitals$Systolic)
data_full_vitals$Diastolic=as.numeric(data_full_vitals$Diastolic)

data_all_vitals=rbind(data_full_vitals, data_vitals)

```

#Diastolic BP
```{r}
#[X] Diastolic BP
BPDiaNonInvasive = data_all_vitals%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(prenatal_bp_date<= pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(Mean_DiastolicBP = mean(Diastolic, na.rm = T))%>%
  select(mom_id, Mean_DiastolicBP)
          
#Join Data
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(BPDiaNonInvasive)

```

#Systolic BP
```{r}
#[X] Systolic BP
BPSysNonInvasive = data_all_vitals%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(prenatal_bp_date<= pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(Mean_SystolicBP = mean(Systolic, na.rm = T))%>%
  select(mom_id, Mean_SystolicBP)
          
#Join Data
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(BPSysNonInvasive)

```

## Diastolic BP Second Visit
```{r}
#[X] Diastolic BP First Visit (0-12 Weeks)
BPDiaNonInvasive_FirstVisit = data_all_vitals%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(prenatal_bp_date<= pregnancy_start_date+84)%>%
  group_by(mom_id)%>%
  summarise(BPDiaMean_FirstVisit = mean(Diastolic, na.rm = T))%>%
  select(mom_id, BPDiaMean_FirstVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(BPDiaNonInvasive_FirstVisit)

#[X] Diastolic BP Second Visit (12-16 Weeks)
BPDiaNonInvasive_SecondVisit = data_all_vitals%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(prenatal_bp_date >= pregnancy_start_date+85 & prenatal_bp_date<=pregnancy_start_date+112)%>%
  group_by(mom_id)%>%
  summarise(BPDiaMean_SecondVisit = mean(Diastolic, na.rm = T))%>%
  select(mom_id, BPDiaMean_SecondVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(BPDiaNonInvasive_SecondVisit)

timetodiagnosis_v1$BPDiaMean_SecondVisit[!timetodiagnosis_v1$mom_id %in% mom_visit2encounters] <- "novisit"
timetodiagnosis_v1=timetodiagnosis_v1%>%
  mutate(BPDiaMean_SecondVisit = ifelse(is.na(BPDiaMean_SecondVisit), BPDiaMean_FirstVisit, BPDiaMean_SecondVisit))
timetodiagnosis_v1$BPDiaMean_SecondVisit[timetodiagnosis_v1$BPDiaMean_SecondVisit  == "novisit"] <- NA

#[X] Diastolic BP Third Visit (16-20 Weeks)
BPDiaNonInvasive_ThirdVisit = data_all_vitals%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(prenatal_bp_date >= pregnancy_start_date+113 & prenatal_bp_date<=pregnancy_start_date+140)%>%
  group_by(mom_id)%>%
  summarise(BPDiaMean_ThirdVisit = mean(Diastolic, na.rm = T))%>%
  select(mom_id, BPDiaMean_ThirdVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(BPDiaNonInvasive_ThirdVisit)

timetodiagnosis_v1$BPDiaMean_ThirdVisit[!timetodiagnosis_v1$mom_id %in% mom_visit3encounters] <- "novisit"
timetodiagnosis_v1=timetodiagnosis_v1%>%
  mutate(BPDiaMean_ThirdVisit = ifelse(is.na(BPDiaMean_ThirdVisit), BPDiaMean_SecondVisit, BPDiaMean_ThirdVisit))
timetodiagnosis_v1$BPDiaMean_ThirdVisit[timetodiagnosis_v1$BPDiaMean_ThirdVisit  == "novisit"] <- NA
```



```{r}
### Mean MCH First and Second Visit

Mean_Corpuscular_Hgb_FirstVisit = labs%>%
  filter(lab_name == "MCH")%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 <= pregnancy_start_date+84)%>%
  group_by(mom_id)%>%
  summarise(Mean_MCH_FirstVisit = mean(value, na.rm=TRUE))%>%
  select(mom_id, Mean_MCH_FirstVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(Mean_Corpuscular_Hgb_FirstVisit,  by=c("mom_id"))

Mean_Corpuscular_Hgb_SecondVisit = labs%>%
  filter(lab_name == "MCH")%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 >= pregnancy_start_date+85 & lab_date2 <=pregnancy_start_date+112)%>%
  group_by(mom_id)%>%
  summarise(Mean_MCH_SecondVisit = mean(value, na.rm=TRUE))%>%
  select(mom_id, Mean_MCH_SecondVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(Mean_Corpuscular_Hgb_SecondVisit,  by=c("mom_id"))

timetodiagnosis_v1$Mean_MCH_SecondVisit[!timetodiagnosis_v1$mom_id %in% mom_visit2encounters] <- "novisit"
timetodiagnosis_v1=timetodiagnosis_v1%>%
  mutate(Mean_MCH_SecondVisit = ifelse(is.na(Mean_MCH_SecondVisit), Mean_MCH_FirstVisit, Mean_MCH_SecondVisit))
timetodiagnosis_v1$Mean_MCH_SecondVisit[timetodiagnosis_v1$Mean_MCH_SecondVisit  == "novisit"] <- NA

# MCHC MCHC Visit
MCHC_FirstVisit= labs%>%
  filter(grepl("MCHC", lab_name))%>%
  mutate(value = as.numeric(value))%>%
  select(mom_id, lab_date2,value)%>%
  inner_join(timetodiagnosis_v1,by=c("mom_id"))%>%
  filter(lab_date2 <= pregnancy_start_date+84)%>%
  group_by(mom_id)%>%
  summarise(Mean_MCHC_FirstVisit=mean(value, na.rm=TRUE))%>%
  select(mom_id,Mean_MCHC_FirstVisit)
timetodiagnosis_v1 = timetodiagnosis_v1%>%left_join(MCHC_FirstVisit,  by=c("mom_id"))

```

```{r}
timetodiagnosis_v1=timetodiagnosis_v1[rowSums(is.na(timetodiagnosis_v1[83:87])) <5L,]

timetodiagnosis_v1=timetodiagnosis_v1%>%
  select(7,8,22,71:92)

timetodiagnosis_vA=timetodiagnosis_v1%>%
  select(-Min_Hematocrit, BPDiaMean_FirstVisit)

# fill NA with mice imputation
timetodiagnosis_vA =do.call(data.frame,lapply(timetodiagnosis_vA, function(x) replace(x, is.infinite(x),NA)))
timetodiagnosis_vA_mice = mice(timetodiagnosis_vA,m=1)
timetodiagnosis_v2 = complete(timetodiagnosis_vA_mice)
```

#Prep Data
```{r}

num_var=c("Min_Hematocrit", "Max_WBCC", "Min_MCHC", "Mean_DiastolicBP", "Mean_SystolicBP", "Mean_MCH_FirstVisit", "Mean_MCH_SecondVisit", "BPDiaMean_FirstVisit", "BPDiaMean_SecondVisit", "BPDiaMean_ThirdVisit", "Mean_MCHC_FirstVisit")

for(i in c(1:ncol(timetodiagnosis_v2))){
  if(colnames(timetodiagnosis_v2)[i]%in%num_var){
    timetodiagnosis_v2[,i] = scale(timetodiagnosis_v2[,i], center = F)
  }
}

#log-transform all skewed numeric variables
for(i in c(1:ncol(timetodiagnosis_v2))){
  if(colnames(timetodiagnosis_v2)[i]%in%num_var){
    timetodiagnosis_v2[,i] = log(timetodiagnosis_v2[,i]+1)
  }
}
```


```{r}
# file name

timetodiagnosis_v2=timetodiagnosis_v2%>%
  select(7,8,42,71:87)

timetodiagnosis_v2=timetodiagnosis_v2%>%
  mutate_all(funs(as.numeric(as.character(.))))

file_name="timetodiagnosis_v2.rda"
data_export_directory=paste0("C:/Users/haile/OneDrive/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
timetodiagnosis_v2 %>% save(timetodiagnosis_v2, file=data_export_path)

```