---
title: "Analysis - Scatterplot"
author: "Hailey Ballard"
date: "1/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Hailey Ballard
# Date:        January 19, 2022
# IRB:         UF Health EHR 
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073  

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# objective: Generate scatterplot of PE diagnosis type versus gestational age.  

```


```{r, include=FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(keyringr)
library(tidyverse)
library(redcapAPI)
library(REDCapR)
library(dplyr)
library(plyr)
library(ggplot2)
```

```{r, include=FALSE}
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v9.rda")
data=delivery_final_v9

```

```{r, message=FALSE}

data$pe_time<-ifelse(data$pe_early == 1, "Early", "Late")

data$pe_strength<-ifelse(data$pe_severe == 1, "Severe", "Mild")

```

```{r, message=FALSE}
x<-data$pe_time
y<-data$gestational_age

boxplot(y~x, main = "Time of PE Diagnosis vs. Gestational Age", xlab = "Time of PE Diagnosis", ylab = "Gestational Age (Weeks)")

```

```{r, message=FALSE}
x<-data$pe_strength
y<-data$gestational_age

boxplot(y~x, main = "Severity of PE Diagnosis vs. Gestational Age", xlab = "Severity of PE Diagnosis", ylab = "Gestational Age (Weeks)")

```

