```{r}
# cox-ph EOPE model validation
library(glmnet)
library(survival)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(survminer)
library(tidyverse)
library(dplyr)
load("~/ehr-preeclampsia-model/data/processed/delivery_linked_v9.rda")


names(delivery_final_v9)[names(delivery_final_v9)== "parity"]<-"EPIS_PARA_COUNT"
names(delivery_final_v9)[names(delivery_final_v9)== "gravidity"]<-"EPIS_GRAVIDA_COUNT"
names(delivery_final_v9)[names(delivery_final_v9)== "mom_age_delivery"]<-"age"
delivery_final_v9=delivery_final_v9%>%
  mutate(NUMBER_OF_FETUSES=recode(multgest_dx_subcategory,
                                  twin="2", 
                                  triplet="3",
                                  multiple="3",
                                  quadruplet="3",
                                  .missing = "1"))

#filter dataset to diag_GA < 34 weeks
eope=delivery_final_v9%>%
  filter(!diag_GA>238)
  


# load UF validation set 
df = eope

# convert zeros in time_to_deliver to 0.5
for(i in c(1:nrow(df))){
  if(df$time_to_deliver[i] == 0){
    df$time_to_deliver[i] = 0.5
  }
}



df$NUMBER_OF_FETUSES<-as.numeric(df$NUMBER_OF_FETUSES)
df$SeverePE<-as.numeric(df$SeverePE)
df$creatinine_value<-as.numeric(df$creatinine_value)
df$Platelet_Count<-as.numeric(df$Platelet_Count)
df$past_pe<-as.numeric(df$past_pe)
df$time_to_deliver<-as.numeric(df$time_to_deliver)


df=df[-c(1:6,10:23)]
#scale all numeric variables except time_to_deliver
for(i in c(1:3, 6,18:38)){
  df[,i]=scale(df[,i],center=F)
}

xtest = data.matrix(df%>%dplyr::select(-time_to_deliver))
ytest = df%>%dplyr::select(time_to_deliver)
ytest = data.frame(time = unlist(ytest), status = rep(1, length(ytest)))
colnames(ytest)[1] = "time"
ytest = as.matrix(ytest)

train_ridge <-cv.glmnet(xtest, ytest, nfolds = 5, family = "cox", alpha = 0)
train_theta = predict(train_ridge, xtest, s=train_ridge$lambda.min,type='link')
cindex_ridge_train = Cindex(train_theta, ytest)
cindex_ridge_train

predict(train_ridge, type="coef")

```

```{r}
library(glmnet)
library(survival)
library(dplyr)

# load data

# scale all numeric variables except for time to deliver
for(i in c(1:12)){
  df[,i] = scale(df[,i], center = F)
}

#split training and testing set
c_index <- data.frame(train = rep(0,5), test = rep(0,5))
train_prop = 0.8
for (i in 0:4){
  set.seed(100*i)
  train_ind <- sample(nrow(df), train_prop*nrow(df))
  
  train <- df[train_ind, ]
  test <- df[-train_ind, ]
  
  ytime_train <- train$time_to_deliver
  y_train = data.frame(time = ytime_train, status = rep(1, length(ytime_train)))
  colnames(y_train)[1] = "time"
  y_train = as.matrix(y_train)
  x_train <- data.matrix(train%>%dplyr::select(-time_to_deliver))
  
  ytime_test <- test$time_to_deliver
  y_test = data.frame(time = ytime_test, status = rep(1, length(ytime_test)))
  colnames(y_test)[1] = "time"
  y_test = as.matrix(y_test)
  x_test <- data.matrix(test%>%dplyr::select(-time_to_deliver))
 
  
  train_ridge <-cv.glmnet(x_train, y_train, nfolds = 5, family = "cox", alpha = 0)
  train_coef = coef(train_ridge)
  train_theta = predict(train_ridge, x_train, s=train_ridge$lambda.min,type='link')
  cindex_ridge_train = Cindex(train_theta, y_train)
  
  test_ridge <- predict(train_ridge, x_test ,s=train_ridge$lambda.min,type='link')
  cindex_ridge_test <- round(Cindex(test_ridge, y_test),3)
  c_index$train[i+1] = cindex_ridge_train
  c_index$test[i+1] = cindex_ridge_test

}
c_index





```