---
title: "getData: linkage"
author: "Dominick Lemas"
date: "01/05/2022"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas & Hailey Ballard 
# Start Date:        January 05, 2022 
# Last Modified:      
# IRB:               IRB protocol IRB201601899  
#                    
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Pull mom-baby linkage data 
#  (2) save as an *.rda object for downstream analysis 

```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(keyringr)
library(tidyverse)
library(redcapAPI)
library(REDCapR)
library(dplyr)
library(plyr)
library(ggplot2)

```

```{r, message=FALSE}
# Windows
 source("~/ehr-preeclampsia-model/code/utils/utils.R")
 source("~/ehr-preeclampsia-model/code/utils/params.R")
 api_token=get_API_token("redcap_ehr2")

# API and URL
uri='https://redcap.ctsi.ufl.edu/redcap/api/'
rcon <- redcapConnection(url=uri, token=api_token)

```

```{r, message=FALSE}

# redcap variables

variables=c("part_id","mom_id","baby_id")

# column types.
col_types <- readr::cols(
      part_id  = readr::col_character(),
      redcap_event_name = readr::col_factor(),
      redcap_repeat_instrument = readr::col_factor(),
      redcap_repeat_instance = readr::col_factor(),
      mom_id  = readr::col_character(),
      baby_id = readr::col_character()
      )

# participant records
records=part_id_list

```

```{r, message=FALSE}
# This data pull works: changed the batch size to very small

start_time = Sys.time()
 redcap_data=redcap_read(batch_size=5, 
                            redcap_uri=uri, 
                            token=api_token,
                            records=records,
                            fields=variables,
                            col_types=col_types)$data %>% drop_na() %>% as_tibble()
end_time = Sys.time()
end_time - start_time

length(unique(redcap_data$part_id))

df=redcap_data 

```

```{r, message=FALSE}
## EXPORT to Sharedrive

# file name
file_name="baby_delivery.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
data_export_path=paste0(data_export_directory,file_name)
df %>% save(df, file=data_export_path)

```