---
title: "IDR-to-RDA: linkage"
author: "Dominick J. Lemas"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas 
# Start Date:        January 05, 2022 
# Last Modified:      
# IRB:               IRB protocol IRB201601899 
#
# version: R 4.1.2 (2021-11-01)
# version: Rstudio 2021.09.1 Build 372 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Process IDR data. 
#  (2) Outputs data as RDA object for downstream analysis. 

```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(readxl)
library(tidyr)
library(dplyr)
library(tidyverse)
library(lubridate)

```

```{r, echo=FALSE, warning=FALSE}

# **************************************************************************** #
# ***************                baby_mom_at_birth_with_payer.csv                                             
# **************************************************************************** #
# rows:            28530
# cols:            20 
# unique baby id:  28530
# unique mom id:   22075

# EXTRACT DATA FROM EXCEL

# import variables
n_max=1000000
data_file_name="baby_mom_at_birth_with_payer.csv"
# data_dir=paste0("~/ehr-database/data/raw/dataset_09_2021/")
data_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/dataset_09_2021/")
data_import_path=paste0(data_dir,data_file_name)

# read data
delivery=read_csv(data_import_path, col_types = cols()) %>%
  dplyr::rename(baby_id = `Deidentified_baby_ID`, 
               baby_race=Race,
               baby_ethnicity=Ethnicity, 
               part_dob=`Date of Delivery`,
               baby_birth_wt_gr=`Birth Weight`,
               delivery_mode.raw=`Pediatric Delivery Type`,
               delivery_admit_source=`Admit Source`,
               baby_gest_age=`Pediatric Gestational Age`, 
               part_gender=Sex, 
               mom_id=Deidentified_mom_ID,
               delivery_admit_date=`Admit Date_mom`, 
               mom_race=Race_mom,
               mom_ethnicity=Ethnicity_mom,
               mom_age_delivery=`Age at Encounter_mom`,
               health_insurance=Payer_mom,
               mom_admit_height_in=`Admit Height (in)`,
               mom_admit_weight_lbs=`Admit Weight (lbs)`,
               mom_admit_weight_kgs=`Admit Weight (kg)`,
               mom_admit_height_cm=`Admit Height (cm)`,
               mom_admit_bmi=`Admit BMI` )

# select variables of interest
data_select=delivery %>%
  select(baby_id,part_dob,baby_gest_age,mom_age_delivery,
         mom_id,delivery_admit_date)

# FORMAT
data_ready = data_select %>%
  mutate(delivery_admit_date=mdy(delivery_admit_date),
         part_dob=mdy_hm(part_dob),
         gest_start_date=as_date(part_dob) %m-% months(19)) %>%
  mutate(baby_id=paste0("baby-",baby_id),
         mom_id=paste0("mom-",mom_id),
         part_id=baby_id)  %>% 
  arrange(part_id, delivery_admit_date) %>%
  group_by(part_id,delivery_admit_date) %>% 
  select("part_id",everything())

```

```{r, echo=FALSE, warning=FALSE}

## EXPORT to Sharedrive

delivery=data_ready

# file name
file_name="mombaby_delivery_raw.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
# data_export_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/project/pe_prediction/")
data_export_path=paste0(data_export_directory,file_name)
delivery %>% save(delivery, file=data_export_path)

```