---
title: 'IDR-to-RedCap: mom mortality and comorbidity codes'
output: html_document
---


```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        January 05, 2022 
# Last Modified:      
# IRB:               IRB protocol IRB201601899 
#                    
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Process IDR data. 
#  (2) Outputs data as RDA object for downstream analysis

```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(readxl)
library(tidyr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(stringr)

```


```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                mom-diagnosis codes                                            
# **************************************************************************** #
# rows:            24249
# cols:            5 
# unique baby id:  1341
# repeat:          1-539
# ICD9/10:         

# import variables
n_max=100000000
# data_dir=paste0("~/ehr-database/data/raw/dataset_10_2021/")
data_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/dataset_10_2021/")

# import data-01
data_file_name="mom_diagnosis_ICD9.csv"
data_import_path=paste0(data_dir,data_file_name)
data01=read_csv(data_import_path, col_types = cols()) %>% 
  rename(mom_id = `Deidentified_mom_ID`, 
         perinatal_dx_date = `Diagnosis Start Date`,
         perinatal_dx_code = `Diagnosis Code`,
         perinatal_dx_descrip = `Diagnosis Description`,
         perinatal_dx_type = `Diagnosis Type`) %>%
  mutate(perinatal_dx_code=as.character(perinatal_dx_code),
         perinatal_icd_code="ICD9")

# import data-02
data_file_name="mom_diagnosis_ICD10.csv"
data_import_path=paste0(data_dir,data_file_name)
data02=read_csv(data_import_path, col_types = cols()) %>% 
  rename(mom_id = `Deidentified_mom_ID`, 
         perinatal_dx_date = `Diagnosis Start Date`,
         perinatal_dx_code = `Diagnosis Code`,
         perinatal_dx_descrip = `Diagnosis Description`,
         perinatal_dx_type = `Diagnosis Type`) %>%
  mutate(perinatal_dx_code=as.character(perinatal_dx_code),
         perinatal_icd_code="ICD10")

# combine data-sets
newdata=bind_rows(data01, data02) 

# FORMAT
data_ready = newdata %>%
  mutate(mom_id=paste0("mom-",mom_id),
         part_id=mom_id)  %>% 
  mutate(perinatal_dx_code=as_factor(perinatal_dx_code)) %>%
  arrange(part_id, perinatal_dx_date) %>%
  group_by(part_id,perinatal_dx_date) %>% 
  select("part_id",everything())

```

```{r, warning=FALSE, echo=FALSE}

  
## EXPORT to Sharedrive: RDA Object

df=data_ready

# file name
file_name="mom_perinatal_raw.rda"
data_export_directory=paste0("~/ehr-preeclampsia-model/data/processed/") 
# data_export_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/project/pe_prediction/")
data_export_path=paste0(data_export_directory,file_name)
df %>% save(df, file=data_export_path)


```

```{r, warning=FALSE, echo=FALSE}

  
## EXPORT to Sharedrive: CSV with ICD9/10 CODES

df_codes=data_ready %>% ungroup() %>%
  select(perinatal_dx_code,perinatal_dx_descrip,perinatal_icd_code) %>%
  distinct() %>% arrange(perinatal_dx_code)  

# file name
file_name="perinatal_ICD_codes_rawdata_01_2022.csv"
data_export_directory=paste0("~/ehr-preeclampsia-model/documents/datadictionary/") 
# data_export_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/project/pe_prediction/")
data_export_path=paste0(data_export_directory,file_name)
write_csv(df_codes, file=data_export_path)


```